fixtures:
    forge_modules:
        stdlib: "puppetlabs/stdlib"
        inifile: "puppetlabs/inifile"
        puppet_authorization: "puppetlabs/puppet_authorization"
        facts: "puppetlabs/facts"
    repositories:
        provision: 'https://github.com/puppetlabs/provision.git'
        puppet_agent: 
            repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
            ref: v4.13.0
    symlinks:
        node_encrypt: "#{source_dir}"
